### ISSUE TITLE
Error faced during docker-compose up

### ISSUE THREAD

**Issue by kushagra2jindal** [jimmygchen/devnet-v3#2]
#0 799.0 Caused by:
#0 799.0   process didn't exit successfully: `/lighthouse/target/release/build/deposit_contract-c1f8bec116214c74/build-script-build` (exit status: 101)
#0 799.0   --- stderr
#0 799.0   thread 'main' panicked at 'No abi file found. Failed to download from github: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("raw.githubusercontent.com")), port: None, path: "/ethereum/eth2.0-specs/v0.12.1/deposit_contract/contracts/validator_registration.json", query: None, fragment: None }, source: TimedOut }', common/deposit_contract/build.rs:68:19
#0 799.0   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#0 799.0 warning: build failed, waiting for other jobs to finish...
#0 822.0 error: failed to compile `lighthouse v4.1.0 (/lighthouse/lighthouse)`, intermediate artifacts can be found at `/lighthouse/target`
#0 824.2 make: *** [Makefile:48: install] Error 101
------
failed to solve: process "/bin/sh -c bash -c \"git clone https://github.com/realbigsean/lighthouse.git && cd lighthouse && git checkout devnetv5 && make\"" did not complete successfully: exit code: 2

**Comment by jimmygchen** [comment]
Hi this seems like a timeout issue trying to download the deposit contract from spec repo - this is required as part of the lighthouse build. Can you check you internet connection and try again?

**Comment by PabloCastellano** [comment]
Also, devnet6 is here now

**Comment by kushagra2jindal** [comment]
Thanks for the udpate, @PabloCastellano will try it today.

**Comment by kushagra2jindal** [comment]
@PabloCastellano, is there any guide like this https://hackmd.io/@jimmygchen/H1XUtBIfn by you for the devnet6?

**Comment by PabloCastellano** [comment]
@kushagra2jindal This repository actually works with devnet6

**Comment by jimmygchen** [comment]
@kushagra2jindal let me know if you still have issues with this. Will close this issue for now.
