### ISSUE TITLE
Failed docker-compose up

### ISSUE THREAD

**Issue by syntrust** [jimmygchen/devnet-v3#3]
Hi Jimmy,
Many thanks for your work on EIP-4844 devnet! I was working happily with the devnet 5 nodes setup with your instruction (https://hackmd.io/@jimmygchen/H1XUtBIfn), but with devnet 6 with the latest update, I got the following error:
```
Creating eip4844-devnet_geth_1       ... done
Creating eip4844-devnet_lighthouse_1 ... done
Attaching to eip4844-devnet_lighthouse_1, eip4844-devnet_geth_1
lighthouse_1  | Jun 16 02:46:29.916 INFO Logging to file                         path: "/data/beacon/logs/beacon.log"
lighthouse_1  | Jun 16 02:46:29.917 INFO Lighthouse started                      version: Lighthouse/v4.2.0-29b7737
lighthouse_1  | Jun 16 02:46:29.917 INFO Configured for network                  name: custom (/config/testnet)
lighthouse_1  | Jun 16 02:46:29.917 INFO Data directory initialised              datadir: /data
lighthouse_1  | Jun 16 02:46:29.918 INFO Deposit contract                        address: 0x6f22ffbc56eff051aecf839396dd1ed9ad6bba9d, deploy_block: 0
lighthouse_1  | Jun 16 02:46:29.922 INFO Hot-Cold DB initialized                 split_state: 0x738239de61848accbc24eea6801fc37ac60f6fec9f719a1997295045ed498565, split_slot: 247776, service: freezer_db
lighthouse_1  | Jun 16 02:46:29.922 INFO Blobs DB initialized                    path: None, use separate blobs db: false, service: freezer_db
lighthouse_1  | Jun 16 02:46:29.922 DEBG Attempting schema migration             to_version: 17, from_version: 17, service: freezer_db
lighthouse_1  | Jun 16 02:46:29.922 INFO Blob info loaded from disk              oldest_blob_slot: Some(Slot(116768)), service: freezer_db
lighthouse_1  | Jun 16 02:46:29.923 DEBG Loaded execution endpoint               jwt_path: "/config/jwtsecret", endpoint: http://geth:8551/, service: exec
lighthouse_1  | Jun 16 02:46:29.927 INFO Starting beacon chain                   method: resume, service: beacon
lighthouse_1  | Jun 16 02:46:29.928 DEBG Restoring fork choice from persisted    contains_invalid_payloads: false, reset_payload_statuses: OnlyWithInvalidPayload, service: beacon
geth_1        | INFO [06-16|02:46:29.975] Maximum peer count                       ETH=50 LES=0 total=50
geth_1        | INFO [06-16|02:46:29.976] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
geth_1        | INFO [06-16|02:46:29.977] Set global gas cap                       cap=50,000,000
geth_1        | INFO [06-16|02:46:29.978] Initializing the KZG library             backend=gokzg
geth_1        | INFO [06-16|02:46:29.991] Using leveldb as the backing database
geth_1        | INFO [06-16|02:46:29.991] Allocated cache and file handles         database=/db/geth/chaindata cache=16.00MiB handles=16
geth_1        | INFO [06-16|02:46:29.994] Using LevelDB as the backing database
geth_1        | INFO [06-16|02:46:29.994] Opened ancient database                  database=/db/geth/chaindata/ancient/chain readonly=false
geth_1        | Fatal: Failed to write genesis block: database contains incompatible genesis (have 8aa19a93cdc8cd78b8f847150515ed05245083770b6946f118d14952f2885db3, new 50ad7c6870979376bfcc19e12220e4f86dec89474761b1041daa76860000e085)
geth_1        | Fatal: Failed to write genesis block: database contains incompatible genesis (have 8aa19a93cdc8cd78b8f847150515ed05245083770b6946f118d14952f2885db3, new 50ad7c6870979376bfcc19e12220e4f86dec89474761b1041daa76860000e085)
lighthouse_1  | Jun 16 02:46:30.036 INFO Block production enabled                method: json rpc via http, endpoint: Auth { endpoint: "http://geth:8551/", jwt_path: "/config/jwtsecret", jwt_id: None, jwt_version: None }
lighthouse_1  | Jun 16 02:46:30.045 DEBG eth1 endpoint error                     error: eth_chainId call failed Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("geth")), port: Some(8551), path: "/", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 111, kind: ConnectionRefused, message: "Connection refused" })) }), endpoint: http://geth:8551/, auth=true, service: deposit_contract_rpc
lighthouse_1  | Jun 16 02:46:30.045 WARN Error connecting to eth1 node endpoint  endpoint: http://geth:8551/, auth=true, service: deposit_contract_rpc
lighthouse_1  | Jun 16 02:46:30.045 ERRO Error updating deposit contract cache   error: Invalid endpoint state: RequestFailed("eth_chainId call failed Reqwest(reqwest::Error { kind: Request, url: Url { scheme: \"http\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"geth\")), port: Some(8551), path: \"/\", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError(\"tcp connect error\", Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })) })"), retry_millis: 60000, service: deposit_contract_rpc
geth_1        | INFO [06-16|02:46:30.053] Maximum peer count                       ETH=50 LES=0 total=50
geth_1        | INFO [06-16|02:46:30.055] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
geth_1        | DEBUG[06-16|02:46:30.055] FS scan times                            list="16.24µs" set=371ns diff="1.062µs"
geth_1        | DEBUG[06-16|02:46:30.056] Sanitizing Go's GC trigger               percent=100
geth_1        | INFO [06-16|02:46:30.056] Set global gas cap                       cap=50,000,000
geth_1        | INFO [06-16|02:46:30.056] Initializing the KZG library             backend=gokzg
geth_1        | INFO [06-16|02:46:30.070] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
geth_1        | INFO [06-16|02:46:30.070] Using leveldb as the backing database
geth_1        | INFO [06-16|02:46:30.070] Allocated cache and file handles         database=/db/geth/chaindata cache=512.00MiB handles=524,288
geth_1        | INFO [06-16|02:46:30.075] Using LevelDB as the backing database
geth_1        | DEBUG[06-16|02:46:30.075] Chain freezer table opened               database=/db/geth/chaindata/ancient/chain table=bodies items=78230 size=2.31MiB
geth_1        | DEBUG[06-16|02:46:30.075] Chain freezer table opened               database=/db/geth/chaindata/ancient/chain table=receipts items=78230 size=320.06KiB
geth_1        | DEBUG[06-16|02:46:30.075] Chain freezer table opened               database=/db/geth/chaindata/ancient/chain table=diffs    items=78230 size=76.40KiB
geth_1        | DEBUG[06-16|02:46:30.075] Chain freezer table opened               database=/db/geth/chaindata/ancient/chain table=headers  items=78230 size=20.41MiB
geth_1        | DEBUG[06-16|02:46:30.075] Chain freezer table opened               database=/db/geth/chaindata/ancient/chain table=hashes   items=78230 size=2.39MiB
geth_1        | INFO [06-16|02:46:30.075] Opened ancient database                  database=/db/geth/chaindata/ancient/chain readonly=false
geth_1        | DEBUG[06-16|02:46:30.075] Ancient blocks frozen already            number=168,229 hash=9ac939..fcab53 frozen=78230
geth_1        | Fatal: Failed to register the Ethereum service: ethash is only supported as a historical component of already merged networks
geth_1        | Fatal: Failed to register the Ethereum service: ethash is only supported as a historical component of already merged networks
lighthouse_1  | Jun 16 02:46:30.096 ERRO Error decoding head block               message: This node has likely missed a hard fork. It will try to revert the invalid blocks and keep running, but any stray blocks and states will not be deleted. Long-term you should consider re-syncing this node., service: beacon
lighthouse_1  | Jun 16 02:46:30.096 WARN Reverting invalid head block            fork_epoch: 2, target_fork: deneb, service: beacon
lighthouse_1  | Jun 16 02:46:30.097 CRIT Failed to start beacon node             reason: Failed to build beacon chain: Error fetching blocks to revert: SszDecodeError(OffsetSkipsVariableBytes(392)). The database could be corrupt. Check its file permissions or consider deleting it by running with the --purge-db flag.
lighthouse_1  | Jun 16 02:46:30.097 INFO Internal shutdown received              reason: Failed to start beacon node
lighthouse_1  | Jun 16 02:46:30.097 INFO Shutting down..                         reason: Failure("Failed to start beacon node")
lighthouse_1  | Failed to start beacon node
```
I've already removed all old images and containers. Is there any cache I should clean on my host as well? 
Thanks!

**Comment by jimmygchen** [comment]
Hi @syntrust 

Thanks for reporting this - I'm not able to reproduce this myself. If you were running devnet-5 before, you'll have to rebuild the images before starting up. Can you try this and let me know if it works?

```
docker-compose build --no-cache
docker-compose up -d
```

**Comment by jimmygchen** [comment]
I've updated the repo again as devnet-6 has been re-launched, you'll have to rebuild the images with:

```
docker-compose build --no-cache
```

**Comment by syntrust** [comment]
> Hi @syntrust
> 
> Thanks for reporting this - I'm not able to reproduce this myself. If you were running devnet-5 before, you'll have to rebuild the images before starting up. Can you try this and let me know if it works?
> 
> ```
> docker-compose build --no-cache
> docker-compose up -d
> ```

Thanks @jimmygchen, the 2 commands ran successfully but the same error appeared when starting up. 
Now I was able to start up on another machine with the latest build. Still trying to connect to some peers...

**Comment by jimmygchen** [comment]
> > Hi @syntrust
> > Thanks for reporting this - I'm not able to reproduce this myself. If you were running devnet-5 before, you'll have to rebuild the images before starting up. Can you try this and let me know if it works?
> > ```
> > docker-compose build --no-cache
> > docker-compose up -d
> > ```
> 
> Thanks @jimmygchen, the 2 commands ran successfully but the same error appeared when starting up. Now I was able to start up on another machine with the latest build. Still trying to connect to some peers...

oh if you've ran on an older devnet you'll need to clear the old databases. Easiest way is probably shutting it down with `docker-compose down -v`

> Now I was able to start up on another machine with the latest build. Still trying to connect to some peers...

I'm having the same issue as well. It seems like that there are some issues with geth forking away on devnet-6, and there are still a few outstanding issues after the relaunch earlier today (see the #interop channel), might have to wait a bit until the bugs are fixed and the network stabilizes.

**Comment by PabloCastellano** [comment]
FYI: we have a working docker-compose setup to run devnet-6 with nethermind+lodestar

Check out https://github.com/Blobscan/4844-devnet

**Comment by syntrust** [comment]
> FYI: we have a working docker-compose setup to run devnet-6 with nethermind+lodestar
> 
> Check out https://github.com/Blobscan/4844-devnet

@PabloCastellano  Thanks for the information! I've followed the readme instruction butI was not sure about the `CHECKPOINT_SYNC_URL` part of `.env` so I leave it blank. And I got the following error:

>nethermind_1  | 2023-06-20 02:05:06.5546|Starting Merge block producer & sealer
lodestar_1    |  ✖ Error: Need a valid 256 bit hex encoded secret undefined pla/P9eVRDwclMM0PTXQpMuIQ2VnIUevwpthYVa1V/VhdS6X9OHbLYOkfzJoTAPd
lodestar_1    |     at extractJwtHexSecret (file:///usr/app/packages/cli/src/util/jwt.ts:6:11)
lodestar_1    |     at Module.parseArgs (file:///usr/app/packages/cli/src/options/beaconNodeOptions/eth1.ts:26:9)
lodestar_1    |     at parseBeaconNodeArgs (file:///usr/app/packages/cli/src/options/beaconNodeOptions/index.ts:30:16)
lodestar_1    |     at beaconHandlerInit (file:///usr/app/packages/cli/src/cmds/beacon/handler.ts:164:51)
lodestar_1    |     at Object.beaconHandler [as handler] (file:///usr/app/packages/cli/src/cmds/beacon/handler.ts:35:90)
lodestar_1    |     at file:///usr/app/packages/cli/node_modules/yargs/build/lib/command.js:206:54
lodestar_1    |     at maybeAsyncResult (file:///usr/app/packages/cli/node_modules/yargs/build/lib/utils/maybe-async-result.js:9:15)
lodestar_1    |     at CommandInstance.handleValidationAndGetResult (file:///usr/app/packages/cli/node_modules/yargs/build/lib/command.js:205:25)
lodestar_1    |     at CommandInstance.applyMiddlewareAndGetResult (file:///usr/app/packages/cli/node_modules/yargs/build/lib/command.js:245:20)
lodestar_1    |     at CommandInstance.runCommand (file:///usr/app/packages/cli/node_modules/yargs/build/lib/command.js:128:20)
lodestar_1    |
nethermind_1  | 2023-06-20 02:05:07.3988|Peers | with known best block: 6 | all: 7 | Active: None | Sleeping: All | Nethermind (83.33 %), Unknown (16.67 %)

Appreciate it if you guys got any clue.

**Comment by jimmygchen** [comment]
@syntrust from your logs it looks like Lodestar wasn't able to find a JWT secret.

FYI - I've pushed another change to this repo with the latest devnet-6 changes, looks like the issues have been fixed and I am able to sync lighthouse/geth to head now.

**Comment by syntrust** [comment]
> @syntrust from your logs it looks like Lodestar wasn't able to find a JWT secret.
> 
> FYI - I've pushed another change to this repo with the latest devnet-6 changes, looks like the issues have been fixed and I am able to sync lighthouse/geth to head now.

It's running perfectly this time, thanks!
